//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// F32.
    /// </summary>
    //  *** Start programmer edit section *** (f32 CustomAttributes)

    //  *** End programmer edit section *** (f32 CustomAttributes)
    [AutoAltered()]
    [Caption("F32")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("f32E", new string[0])]
    [View("f32L", new string[0])]
    public class f32 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (f32 CustomMembers)

        //  *** End programmer edit section *** (f32 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "f32E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View f32E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("f32E", typeof(IIS.mu12.f32));
                }
            }
            
            /// <summary>
            /// "f32L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View f32L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("f32L", typeof(IIS.mu12.f32));
                }
            }
        }
    }
}
